/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        warning: "var(--warning)",
        "warning-foreground": "var(--warning-foreground)",
        "bg-deep": "var(--clr-bg-deep)",
        "bg-screen": "var(--clr-bg-screen)",
        "bg-panel": "var(--clr-bg-panel)",
        "green-dim": "var(--clr-green-dim)",
        "green-mid": "var(--clr-green-mid)",
        "green-base": "var(--clr-green-base)",
        "green-bright": "var(--clr-green-bright)",
        "green-hi": "var(--clr-green-hi)",
        "green-max": "var(--clr-green-max)",
        danger: "var(--clr-danger)",
        "danger-text": "var(--clr-danger-text)",
        "warn-text": "var(--clr-warn-text)",
        bezel: "var(--clr-bezel)",
        "bezel-hi": "var(--clr-bezel-hi)",
        screw: "var(--clr-screw)",
      },
      fontFamily: {
        display: ["Orbitron", "sans-serif"],
        tech: ["Rajdhani", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        "glow-text": "var(--glow-text)",
        "glow-strong": "var(--glow-strong)",
        "glow-subtle": "var(--glow-subtle)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
      },
    },
  },
  plugins: [],
};
